name: aoc
version: 0.1.0.0
github: "Futarimiti/aoc"
license: WTFPL
author: "Carman Fu"
maintainer: "futarimiti@163.com"
copyright: "Carman Fu 2024"
extra-source-files: []
synopsis: My solutions to AOC
category: Other
description: Please see the README on GitHub at <https://github.com/Futarimiti/aoc#readme>
dependencies:
  - base >= 4.7 && < 5
  - data-default
  - search-algorithms
  - multiset
  - split
  - text
  - bytestring
  - monad-logger
  - dbg
  - mtl
  - transformers
  - exceptions
  - lens
  - typed-process
  - containers
  - zippers
  - vector
  - pretty-show
  - template-haskell
  - string-interpolate
  - filepath
  - directory
  - witherable
  - linear
  - matrix
  - unordered-containers
  - hashable
  - comonad
default-extensions:
  - ApplicativeDo
  - TemplateHaskell
  - QuasiQuotes
  - StandaloneDeriving
  - DerivingVia
  - DeriveFunctor
  - GeneralizedNewtypeDeriving
  - DeriveGeneric
  - MultiWayIf
  - PatternSynonyms
  - ViewPatterns
  - OverloadedStrings
  - OverloadedLists
  - TypeApplications
  - LambdaCase
  - RecordWildCards
  - FlexibleContexts
  - ConstraintKinds
  - RankNTypes
  - FlexibleInstances
  - OverloadedLabels
  - ScopedTypeVariables
  - AllowAmbiguousTypes
  - TypeFamilyDependencies
  - FunctionalDependencies
  - StandaloneKindSignatures
  - InstanceSigs
  - UnicodeSyntax
  - PartialTypeSignatures
  - TypeOperators
  - DataKinds
  - BinaryLiterals
  - TransformListComp
  - BlockArguments
data-dir: resources/
data-files:
  - '**/*.txt'
ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wmonomorphism-restriction
  - -Wno-unused-imports
  - -Wno-orphans
  - -Wno-unused-top-binds
library:
  source-dirs:
    - src
    - common
    - meta
